server/dispatch/urls.py
from django.conf.urls.defaults import patterns, url
from dispatch.views import PackageListView, ClientListView, CourierListView, PackageCreateView, CourierCreateView,PackageUpdateView
from dispatch.views import ClientToggleView, CourierToggleView, CourierUpdateView, PackageDetailView, push_test, RunDispatcherView

urlpatterns = patterns('',
   
    url(r'^clients/(?P<pk>\d)/toggle/', ClientToggleView.as_view(), name="client_toggle"),
    url(r'^clients/', ClientListView.as_view(), name="client_list"),

    url(r'^packages/(?P<pk>\d)/edit/', PackageUpdateView.as_view(), name="package_edit"),
    url(r'^packages/(?P<pk>\d)/', PackageDetailView.as_view(), name="package_detail"),
    url(r'^packages/new/', PackageCreateView.as_view(), name="package_add"),
    url(r'^packages/', PackageListView.as_view(), name="package_list"),

    url(r'^couriers/new/', CourierCreateView.as_view(), name="courier_add"),
    url(r'^couriers/(?P<pk>\d)/toggle/', CourierToggleView.as_view(), name="courier_toggle"),
    url(r'^couriers/(?P<pk>\d)/edit/', CourierUpdateView.as_view(), name="courier_edit"),
    url(r'^couriers/', CourierListView.as_view(), name="courier_list"),

    url(r'^push_test/(?P<pk>\d)/(?P<message>\w+)', push_test, name="push_test"),
    url(r'^run/', RunDispatcherView.as_view(), name="run"),

)

server/urls.py
from django.conf.urls.defaults import patterns, include, url
from dispatch.urls import *
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.views.generic.simple import redirect_to
from django.utils.functional import lazy
from server.dispatch.views import ProfileView

reverse_lazy = lazy(reverse, unicode)
admin.autodiscover()

urlpatterns = patterns('',

    #dispacth app urls
    url(r'^dispatch/', include('dispatch.urls')),

    #admin urls
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    #api urls
    url(r'^api/', include('api.urls')),

    #registration+auth app urls
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/profile/', ProfileView.as_view(), name="profile"),

    #redirect to package_list(in dispatch app)
    url(r'^$', redirect_to, {'url': reverse_lazy('package_list')}),

)

server/dispatch/models.py
# -*- coding: utf-8 -*-
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.contrib.auth.models import User, Group
import json

class ETurtleGroup(Group):
    GROUP_ADMIN = 'eturtle_admin'
    GROUP_COURIER = 'courier'
    GROUP_CLIENT = 'client'

    @classmethod
    def get_group_or_raise(cls,group_name):
        try:
            return cls.objects.get(name=group_name)
        except cls.DoesNotExist:
            raise ImproperlyConfigured('You must create the base user groups:(%s,%s,%s)' % (cls.GROUP_ADMIN, cls.GROUP_COURIER, cls.GROUP_CLIENT))

    @classmethod
    def admin(cls):
        return cls.get_group_or_raise(cls.GROUP_ADMIN)

    @classmethod
    def courier(cls):
        return cls.get_group_or_raise(cls.GROUP_COURIER)

    @classmethod
    def client(cls):
        return cls.get_group_or_raise(cls.GROUP_CLIENT)

    class Meta:
        proxy = True

class ETModelBase(models.Model):
    date_created = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now = True)
    class Meta:
        abstract = True

class Courier(ETModelBase, User):
    STATE_IDLE = 1
    STATE_STANDING_BY = 2
    STATE_PENDING = 3
    STATE_SHIPPING = 4

    STATE_CHOICES = (
        (1, 'inaktiv'),
        (2, 'csomagra vár'),
        (3, 'függőben'),
        (4, 'szállít'),
    )
    state = models.IntegerField(choices = STATE_CHOICES, default = 1)

    lat = models.CharField(max_length=20, default='', blank=True)
    lng = models.CharField(max_length=20, default='', blank=True)
    last_pos_update = models.DateTimeField(null=True, blank=True)

    c2dmkey = models.CharField(max_length='256', null=True, blank=True)

    def __unicode__(self):
        return u'%s' % self.username

    class Meta:
        permissions = (
            ("api_access", "Can login via api and access api functions."),
            ("web_access", "Can login via browser and access the web application."),
        )

class ClientManager(models.Manager):
    def get_query_set(self):
        return super(ClientManager, self).get_query_set().filter(groups__name=ETurtleGroup.GROUP_CLIENT)

class Client(User):
    objects = ClientManager()

    def from_user(self, user):
        self.__dict__ = user.__dict__
        return self

    class Meta:
        proxy = True

class Package(ETModelBase):
    STATE_NEW = 1
    STATE_PENDING = 2
    STATE_SHIPPING = 3
    STATE_SHIPPED = 4
    STATE_FAILED = 5

    STATE_ENUM = [
        (1, u'új'),
        (2, u'elfogadásra vár'),
        (3, u'szállítás alatt'),
        (4, u'kiszállítva'),
        (5, u'sikertelen szállítás'),
    ]
    client = models.ForeignKey(Client)

    name = models.CharField(max_length=100)

    source = models.CharField(max_length=100)
    src_lat = models.CharField(max_length=20)
    src_lng = models.CharField(max_length=20)

    destination = models.CharField(max_length=100)
    dst_lat = models.CharField(max_length=20)
    dst_lng = models.CharField(max_length=20)

    state = models.IntegerField(choices = STATE_ENUM, default = 1)

    def serialize(self):
        data={'name':self.name,
               'source':self.source,
               'src_lat':self.src_lat,
               'src_lng':self.src_lng,
               'destination':self.destination,
               'dst_lat':self.dst_lat,
               'dst_lng':self.dst_lng,
               'date_created':self.date_created.isoformat()}
        return json.dumps(data)

    def __unicode__(self):
        return u'%s' % self.name

class Dispatch(ETModelBase):
    STATE_PENDING = 1
    STATE_REJECTED = 2
    STATE_SHIPPING = 3
    STATE_SHIPPED = 4
    STATE_FAILED = 5
    STATE_TIMED_OUT = 6

    STATE_ENUM = [
        (1, 'PENDING'),
        (2, 'REJECTED'),
        (3, 'SHIPPING'),
        (4, 'SHIPPED'),
        (5, 'FAILED'),
        (6, 'TIMED_OUT'),
    ]
    state = models.IntegerField(choices = STATE_ENUM, default = 1)
    courier = models.ForeignKey('Courier')
    package = models.ForeignKey('Package')

    def save(self, force_insert=False, force_update=False, using=None):

        if not self.id and Dispatch.objects.filter(courier=self.courier, state=1).count():
            raise Exception("This user already has a pending dispatch.")

        super(Dispatch,self).save(force_insert=force_insert,
                                  force_update=force_update,
                                  using=using)



    class Meta:
        ordering = ('-date_created',)

    def __unicode__(self):
        return u'%s -> %s' % (self.package, self.courier)

server/dispatch/forms.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User

from dispatch.models import Package, Courier
from django import forms

class PackageForm(forms.ModelForm):
    src_lat = forms.CharField(widget=forms.HiddenInput(), required=False)
    src_lng = forms.CharField(widget=forms.HiddenInput(), required=False)

    dst_lat = forms.CharField(widget=forms.HiddenInput(), required=False)
    dst_lng = forms.CharField(widget=forms.HiddenInput(), required=False)

    def clean(self):
        cleaned_data = self.cleaned_data

        if self.instance:
            if not getattr(self.instance, 'state', None)==Package.STATE_NEW:
                raise forms.ValidationError(u"A csomag már kiosztásra került, most már \
                nem módosítható. Kérjük lépjen kapcsolatba az ügyfélszolgálattal.")
        return cleaned_data
    
    class Meta:
        model = Package
        exclude = ('client','state')

class CourierForm(forms.ModelForm):
    pw1 = forms.CharField( widget=forms.PasswordInput, label=u'Jelszó' )
    pw2 = forms.CharField( widget=forms.PasswordInput, label=u'Jelszó ismét' )

    def clean(self):
        cleaned_data = self.cleaned_data
        pw1 = cleaned_data.get("pw1")
        pw2 = cleaned_data.get("pw2")

        if not pw1==pw2:
            raise forms.ValidationError(u"A két jelszónak meg kell egyeznie!")

        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if User.objects.filter(username=username).count():
            raise forms.ValidationError(u"Már van ilyen nevű felhasználó!")

        return username

    class Meta:
        model = Courier
        fields = ('username','first_name','last_name','pw1','pw2')

class CourierEditForm(forms.ModelForm):
    class Meta:
        model = Courier
        fields = ('first_name','last_name','email')

server/dispatch/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.forms import forms
from django.http import HttpResponse, HttpResponseServerError, HttpResponseForbidden, HttpResponseNotFound, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from dispatch.forms import PackageForm, CourierForm
from dispatch.models import Package, Courier, Client
from dispatch.models import ETurtleGroup as Group
from utils import AdminOr404Mixin, WebLoginRequiredMixin
from registration.signals import user_registered
from django.dispatch import receiver
from dispatcher import run_dispatcher


#signal catch for user registration
from server.dispatch.dispatcher import push
from server.dispatch.forms import CourierEditForm

@receiver(user_registered)
def set_group_of_registered_user(sender, **kwargs):
    user = kwargs.get('user')
    user.groups.add(Group.client())

class PackageListView(WebLoginRequiredMixin, ListView):
    model = Package

    def get_queryset(self):
        queryset = super(PackageListView,self).get_queryset()

        if not self.request.user.has_perm('dispatch.eturtle_admin'):
            queryset = queryset.filter(client = self.request.user)

        return queryset

class PackageUpdateView(WebLoginRequiredMixin, UpdateView):
    form_class = PackageForm
    template_name = 'dispatch/package_edit.html'
    model = Package

    def form_valid(self, form):
        self.package = form.save(commit=False)
        self.package.client = Client().from_user(self.request.user)
        self.package.save()
        return super(PackageUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('package_detail', kwargs={'pk':self.object.pk})

    def get(self, *args, **kwargs):
        handler = super(PackageUpdateView, self).get(*args, **kwargs)
        if not self.get_object().state == Package.STATE_NEW:
            raise Http404()
        return handler


class PackageCreateView(WebLoginRequiredMixin, CreateView):
    form_class = PackageForm
    template_name = 'dispatch/package_create.html'

    def form_valid(self, form):
        self.package = form.save(commit=False)
        self.package.client = Client().from_user(self.request.user)
        self.package.save()
        response = super(PackageCreateView, self).form_valid(form)
        run_dispatcher()
        return response

    def get_success_url(self):
        return reverse('package_detail', kwargs={'pk':self.object.pk})

class PackageDetailView(WebLoginRequiredMixin, DetailView):
    queryset = Package.objects.all()

    def get_queryset(self, queryset=None):
        queryset = super(PackageDetailView,self).get_queryset()

        if not self.request.user.has_perm('dispatch.eturtle_admin'):
            queryset = queryset.filter(client = self.request.user)

        return queryset

class CourierListView(AdminOr404Mixin, ListView):
    model = Courier

class CourierCreateView(WebLoginRequiredMixin, CreateView):
    form_class = CourierForm
    template_name = 'dispatch/courier_create.html'

    def form_valid(self, form):
        self.courier = form.save(commit=False)
        self.courier.set_password(form.cleaned_data.get('pw1'))
        self.courier.save()
        self.courier.groups.add(Group.courier())
        return super(CourierCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('courier_list', kwargs={})

class ClientListView(AdminOr404Mixin, ListView):
    model = Client
    queryset = Client.objects.filter(groups=Group.client)

class ClientToggleView(AdminOr404Mixin, DeleteView):
    model = Client

    def toggle(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active=not self.object.is_active
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get(self, *args, **kwargs):
        return self.toggle(*args, **kwargs)

    def post(self, *args, **kwargs):
        return self.toggle(*args, **kwargs)

    def get_success_url(self):
        return reverse('client_list')

class CourierToggleView(ClientToggleView):
    model = Courier

    def get_success_url(self):
        return reverse('courier_list')

class CourierUpdateView(AdminOr404Mixin, UpdateView):
    model = Courier
    form_class = CourierEditForm

    def get_success_url(self):
        return reverse('courier_list')

class ProfileView(WebLoginRequiredMixin, DetailView):
    def get_object(self, queryset=None):
        return self.request.user

@login_required
def push_test(request,pk,message):
    if not request.user.has_perm('dispatch.eturtle_admin'):
        raise Http404()
    courier = get_object_or_404(Courier, pk=pk)
    x = push(courier, message)

    return HttpResponse('%s' % x)

class RunDispatcherView(AdminOr404Mixin, TemplateView):
    template_name = "dispatch/run.html"

    def get_context_data(self, **kwargs):
        run_dispatcher()
        return super(RunDispatcherView,self).get_context_data(**kwargs)

server/templates/dispatch/client_list.html
{% extends "base.html" %}

{% block client_tab_class %}selected{% endblock %}

{% block content %}

    {% if object_list %}
        <table class="datagrid">
            <tr>
                <th>Név</th>
                <th>Email</th>
                <th>Eddig rendelt</th>
                <th></th>
            </tr>
            {% for client in object_list %}
            <tr{% if not client.is_active %} class="inactive"{% endif %}>
                <td>{{ client.username }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.package_set.count|default:"-" }}</td>
                <td>
                    <a href="{% url client_toggle client.pk %}">

                    {% if not client.pk == user.pk %}
                        {% if client.is_active %}
                            <img src="/static/img/delete.png" alt="delete client"/>
                        {% else %}
                            <img src="/static/img/accept.png" alt="enable client"/>
                        {% endif %}
                    {% endif %}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        Nincs ügyfél.
    {% endif %}
    
{% endblock %}

server/templates/dispatch/courier_create.html
{% extends "base.html" %}

{% block nav %}<span class="nav-button">Futár felvitele</span>{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <table class="form">
        {{ form.as_table }}

        <tr>
            <td colspan="2"><button>Futát felvitele</button><br/></td>
        </tr>
    </table>
</form>
{% endblock %}

server/templates/dispatch/courier_form.html
{% extends "base.html" %}

{% block courier_tab_class %}selected{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <table class="form">
        {{ form.as_table }}

        <tr>
            <td colspan="2"><button>Mentés</button><br/></td>
        </tr>
    </table>
</form>
{% endblock %}

server/templates/dispatch/courier_list.html
{% extends "base.html" %}

{% block courier_tab_class %}selected{% endblock %}

{% block middle_bar %}
    <div id="middle_bar">
        <a href="{% url courier_add %}" class="nav-button selected">Új futár felvitele</a>
    </div>
{% endblock %}

{% block content %}
<div class="left">
    {% if object_list %}
        <table class="datagrid">
            <tr>
                <th>Név</th>
                <th>Állapot</th>
                <th>Pozíció</th>
                <th>Utolsó frissítés</th>
                <th></th>
            </tr>
            {% for courier in object_list %}
            <tr class="courier_row{% if not courier.is_active %} inactive{% endif %}">
                <td class="username">{{ courier.get_full_name }}</td>
                <td>{{ courier.get_state_display }}</td>
                <td class="position">
                    {% if courier.lat and courier.lng %}
                        {{ courier.lat|slice:":8" }}<br/>
                        {{ courier.lng|slice:":8" }}
                    {% endif %}
                </td>
                <td>{{ courier.last_pos_update|timesince }}</td>
                <td>
                    <a href="{% url courier_toggle courier.pk %}">

                    {% if courier.is_active %}
                        <img src="/static/img/delete.png" alt="delete client"/>
                    {% else %}
                        <img src="/static/img/accept.png" alt="enable client"/>
                    {% endif %}
                    </a>

                    <a href="{% url courier_edit courier.pk %}">
                        <img src="/static/img/edit.png" alt="edit client"/>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        Nincs futár.
    {% endif %}
</div>
<div id="map_canvas"></div>
<div class="clearfix"></div>
    
{% endblock %}

{% block extra_script %}
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="/static/js/couriers.js"></script>
{% endblock %}

server/templates/dispatch/package_create.html
{% extends "base.html" %}

{% block nav %}<span class="nav-button">Csomag felvitele</span>{% endblock %}

{% block content %}
<div class="left">
    <form method="post">{% csrf_token %}
    <table class="form">
        {{ form.as_table }}

        <tr>
            <td colspan="2"><button>Kérem a szállítást</button><br/></td>
        </tr>
    </table>
    </form>
</div>
<div id="map_canvas"></div>
<div class="clearfix"></div>

{% endblock %}

{% block extra_script %}
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="/static/js/new_package.js"></script>
{% endblock %}

server/templates/dispatch/package_detail.html
{% extends "base.html" %}

{% block package_tab_class %}selected{% endblock %}

{% block middle_bar %}
    {% if package.state == package.STATE_NEW %}
    <div id="middle_bar">
        <a href="{% url package_edit package.pk %}" class="nav-button selected">Adatok szerkesztése</a>
    </div>
    {% endif %}
{% endblock %}

{% block content %}
<div class="left">
    <table class="form">
        <tr>
            <th>Csomag név</th><td>{{ package.name }}</td>
        </tr>
        <tr>
            <th>Honnan</th><td>{{ package.source }}</td>
        </tr>
        <tr>
            <th>Hova</th><td>{{ package.destination }}</td>
        </tr>
        <tr>
            <th>Állapot</th><td>{{ package.get_state_display }}</td>
        </tr>
        <tr>
            <th>Futár</th>
            <td>
                {% with courier=package.dispatch_set.all.0.courier %}
                    <span id="username">{{ courier|default:"-" }}</span>
                    <input type="hidden" id="latlng" name="lat"
                            value="{{courier.lat}},{{courier.lng}}"/>
                {% endwith %}
            </td>
        </tr>
        <tr>
            <th>Eltelt idő</th><td>{{ package.date_created|timesince }}</td>
        </tr>
    </table>
    <input type="hidden" id="source" name="source" value="{{ package.source }}"/>
    <input type="hidden" id="destination" name="destination" value="{{ package.destination }}"/>

</div>
<div id="map_canvas"></div>
<div class="clearfix"></div>

{% endblock %}

{% block extra_script %}
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="/static/js/package_detail.js"></script>
{% endblock %}

server/templates/dispatch/package_edit.html
{% extends "base.html" %}

{% block package_tab_class %}selected{% endblock %}

{% block content %}
<div class="left">
    <form method="post">{% csrf_token %}
    <table class="form">
        {{ form.as_table }}

        <tr>
            <td colspan="2"><button>Módosítás</button><br/></td>
        </tr>
    </table>
    </form>
</div>
<div id="map_canvas"></div>
<div class="clearfix"></div>

{% endblock %}

{% block extra_script %}
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="/static/js/new_package.js"></script>
{% endblock %}

server/templates/dispatch/package_list.html
{% extends "base.html" %}

{% block package_tab_class %}selected{% endblock %}

{% block middle_bar %}
    <div id="middle_bar">
        <a href="{% url package_add %}" class="nav-button selected">Új csomag felvitele</a>
    </div>
{% endblock %}

{% block content %}

    {% if object_list %}
        <table class="datagrid">
            <tr>
                <th>Ügyfél</th>
                <th>Csomag név</th>
                <th>Állapot</th>
                <th>Futár</th>
                <th>Eltelt idő</th>
            </tr>
            {% for package in object_list %}
            <tr>
                <td>{{ package.client }}</td>
                <td><a href="{% url package_detail package.pk %}">{{ package.name }}</a></td>
                <td>{{ package.get_state_display }}</td>
                <td>{{ package.dispatch_set.all.0.courier|default:"-" }}</td>
                <td>{{ package.date_created|timesince }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        Nincs csomag.
    {% endif %}
    
{% endblock %}

server/templates/dispatch/run.html
{% extends "base.html" %}

{% block content %}
<p>A csomagkiosztás sikeresen lefutott.</p>
{% now "Y.m.j. - H:i:s" %}
{% endblock %}